### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by kifle23** [kifle23/space-travelers-react-group-capstone#25]
- https://github.com/kifle23/space-travelers-react-group-capstone/projects/1
- We are a group of two

**Comment by joskalenda** [comment]
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Team, |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media4.giphy.com/media/gPdC6JQLdJxP9dy3A8/giphy-downsized-medium.gif"/> |

## Highlights

- [ ]... ✅ Tasks assigned
- [ ]... ✅ Setup Kanban

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by algerina** [comment]
Hi team ,

Great job so far you can start working on your project!  

May I highlight the following: 
- [x] Your Kanbam board is etup correctly👏  ✔️ 
- [x] You implemented all the requirements✔️ 





## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_
